import { Source_Serif_4, Oswald, Caveat } from "next/font/google";
import "./globals.css";
import Footer from "./components/general/footer";

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sourceSerif.variable} ${oswald.variable} ${caveat.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
